# action.yml
name: 'commit gitea'
description: 'commit repo to gitea'
inputs:
  username:  # username to use
    description: 'Git username'
    required: true
  password:  # username to use
    description: 'Git password or token'
    required: true
  repo:  # username to use
    description: 'Git repository'
    required: true
  branch:  # username to use
    description: 'Git branch'
    required: true
    default: 'master'

outputs:
  repo: 
    description: 'Git repository'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.repo }}
    - ${{ inputs.branch }}
