on: [push]

jobs:
  test-public-repo:

    runs-on: ubuntu-latest

    name: test

    steps:
    - uses: actions/checkout@v1

    - name: commit repo
      id: commit_repo
      uses: ./github/actions/commit
      with:
        repo: "https://github.com/mego22/dotfiles.git"
